ARG img_version
FROM godot-osx:${img_version}
RUN curl -L -o /tmp/lipo https://github.com/konoui/lipo/releases/latest/download/lipo_Linux_amd64 > /usr/local/bin/lipo && chmod +x /usr/local/bin/lipo
RUN curl -OL https://github.com/godotengine/moltenvk-osxcross/releases/download/vulkan-sdk-1.3.283.0-2/MoltenVK-all.tar && tar -xf MoltenVK-all.tar
RUN mkdir -p "macOS"
RUN mv "MoltenVK/MoltenVK/static" "macOS/lib"
RUN rm -rf "MoltenVK-all.tar"

CMD /bin/bash
