ARG img_version
FROM godot-fedora:${img_version}

ENV GODOT_SDK_LINUX_X86_64=/root/x86_64-godot-linux-gnu_sdk-buildroot
ENV GODOT_SDK_LINUX_X86_32=/root/i686-godot-linux-gnu_sdk-buildroot
ENV GODOT_SDK_LINUX_ARM64=/root/aarch64-godot-linux-gnu_sdk-buildroot
ENV GODOT_SDK_LINUX_ARM32=/root/arm-godot-linux-gnueabihf_sdk-buildroot
ENV BASE_PATH=${PATH}
ENV BASE_URL="https://download.tuxfamily.org/godotengine/toolchains/linux"
ENV VERSION_DATE="2024-08-29"

RUN dnf install -y wayland-devel && \
    curl -LO "${BASE_URL}/${VERSION_DATE}/x86_64-godot-linux-gnu_sdk-buildroot.tar.bz2" && \
    tar xf x86_64-godot-linux-gnu_sdk-buildroot.tar.bz2 && \
    rm -f x86_64-godot-linux-gnu_sdk-buildroot.tar.bz2 && \
    cd x86_64-godot-linux-gnu_sdk-buildroot && \
    ./relocate-sdk.sh && \
    cd /root && \
    curl -LO "${BASE_URL}/${VERSION_DATE}/i686-godot-linux-gnu_sdk-buildroot.tar.bz2" && \
    tar xf i686-godot-linux-gnu_sdk-buildroot.tar.bz2 && \
    rm -f i686-godot-linux-gnu_sdk-buildroot.tar.bz2 && \
    cd i686-godot-linux-gnu_sdk-buildroot && \
    ./relocate-sdk.sh && \
    cd /root && \
    curl -LO "${BASE_URL}/${VERSION_DATE}/aarch64-godot-linux-gnu_sdk-buildroot.tar.bz2" && \
    tar xf aarch64-godot-linux-gnu_sdk-buildroot.tar.bz2 && \
    rm -f aarch64-godot-linux-gnu_sdk-buildroot.tar.bz2 && \
    cd aarch64-godot-linux-gnu_sdk-buildroot && \
    ./relocate-sdk.sh && \
    cd /root && \
    curl -LO "${BASE_URL}/${VERSION_DATE}/arm-godot-linux-gnueabihf_sdk-buildroot.tar.bz2" && \
    tar xf arm-godot-linux-gnueabihf_sdk-buildroot.tar.bz2 && \
    rm -f arm-godot-linux-gnueabihf_sdk-buildroot.tar.bz2 && \
    cd arm-godot-linux-gnueabihf_sdk-buildroot && \
    ./relocate-sdk.sh

CMD /bin/bash
